### PR TITLE
Update ScriptProcessor Bean to @RequestScoped

### PR DESCRIPTION
**Pull request by kevin-mcgoldrick**
## Update ScriptProcessor Bean to @RequestScoped

Please make sure these check boxes are checked before submitting
- [x] ** Squashed Commits **
- [x] ** All Tests Passed ** - ```mvn clean test -P default``` 

** PR review process **
- Requires one +1 from a reviewer
- Repository owners will merge your PR once it is approved.

### CODE REVIEW

**Review by Zakaria-Kofiro — CHANGES_REQUESTED** [review]
Validated script upload via API no longer spiking memory usage, but ran into issues uploading scripts via Tank UI with `ScriptServiceUtil:389 - Error unmarshalling script: null` error

**Comment by kevin-mcgoldrick** [comment]
Excellent find. That must be why it's Dependent. I'll try the other approach in QA.

> Validated script upload via API no longer spiking memory usage, but ran into issues uploading scripts via Tank UI with `ScriptServiceUtil:389 - Error unmarshalling script: null` error

Excellent find, I'll try the other approach.

**Review by Zakaria-Kofiro — APPROVED** [review]
LGTM

**Comment by Zakaria-Kofiro** [comment]
> Validated script upload via API no longer spiking memory usage, but ran into issues uploading scripts via Tank UI with `ScriptServiceUtil:389 - Error unmarshalling script: null` error

Change working as intended, this error is unrelated to the change, arising from re-uploading a specific unfiltered script. It also throws the same error when uploading on `master` branch.

**Pull request merged**
